//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI_lib.SRLTService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRLTService.ASPUploadProcessSoap")]
    public interface ASPUploadProcessSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMSIModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMSIModel(string s_model, string s_marketname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMSIModel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMSIModelAsync(string s_model, string s_marketname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Phone_Area", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Phone_Area(string vCountry, string vType, string vNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Phone_Area", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Phone_AreaAsync(string vCountry, string vType, string vNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Parts_Onhand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Parts_Onhand(string vRC, string vModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Parts_Onhand", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Parts_OnhandAsync(string vRC, string vModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Parts_Price", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Parts_Price(string vRC, string vModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Parts_Price", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Parts_PriceAsync(string vRC, string vModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMSICNModelPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMSICNModelPrice(string vRC, string vModel, string vMarketname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMSICNModelPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetMSICNModelPriceAsync(string vRC, string vModel, string vMarketname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRMArequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string updateRMArequest(MSI_lib.SRLTService.rmaRequest s_newRMA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRMArequest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> updateRMArequestAsync(MSI_lib.SRLTService.rmaRequest s_newRMA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTStatusList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getSRLTStatusList(MSI_lib.SRLTService.QueryFilter qf_cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTStatusList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getSRLTStatusListAsync(MSI_lib.SRLTService.QueryFilter qf_cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getQuotationOBC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getQuotationOBC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getQuotationOBC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getQuotationOBCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getQuotationDeatil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getQuotationDeatil(string vQuotationno, string vRC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getQuotationDeatil", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getQuotationDeatilAsync(string vQuotationno, string vRC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTStatusForIVR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getSRLTStatusForIVR(MSI_lib.SRLTService.QueryFilter vQueryFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTStatusForIVR", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getSRLTStatusForIVRAsync(MSI_lib.SRLTService.QueryFilter vQueryFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTStatusForWeb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getSRLTStatusForWeb(MSI_lib.SRLTService.QueryFilter vQueryFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTStatusForWeb", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getSRLTStatusForWebAsync(MSI_lib.SRLTService.QueryFilter vQueryFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckBookingRMANO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CheckBookingRMANO(string vRMANO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckBookingRMANO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CheckBookingRMANOAsync(string vRMANO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPelicanEDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPelicanEDI(string vrepaircenter, string begindate, string enddate, string inout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPelicanEDI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPelicanEDIAsync(string vrepaircenter, string begindate, string enddate, string inout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOffDate(string vCountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOffDateAsync(string vCountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetServiceInfo(string vCountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetServiceInfoAsync(string vCountry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookingTbl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBookingTbl(string vcountry, string vsc, string begindate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookingTbl", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBookingTblAsync(string vcountry, string vsc, string begindate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickupBookingAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PickupBookingAdd(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickupBookingAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PickupBookingAddAsync(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickupBookingDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PickupBookingDelete(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PickupBookingDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PickupBookingDeleteAsync(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMABookingAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RMABookingAdd(string vsc, string vbookingdate, string vsession, MSI_lib.SRLTService.rmaRequest s_newRMA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMABookingAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RMABookingAddAsync(string vsc, string vbookingdate, string vsession, MSI_lib.SRLTService.rmaRequest s_newRMA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMABookingDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RMABookingDelete(string vcountry, string vsc, string vrc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMABookingDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RMABookingDeleteAsync(string vcountry, string vsc, string vrc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTWarrantyInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getSRLTWarrantyInfo(MSI_lib.SRLTService.QueryFilterH qf_cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSRLTWarrantyInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getSRLTWarrantyInfoAsync(MSI_lib.SRLTService.QueryFilterH qf_cond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chkbarcoderequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string chkbarcoderequest(string vBarcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/chkbarcoderequest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> chkbarcoderequestAsync(string vBarcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createRMArequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MSI_lib.SRLTService.createRMArequestResponse createRMArequest(MSI_lib.SRLTService.createRMArequestRequest request);
        
        // CODEGEN: 正在產生訊息合約，因為此作業具有多個傳回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createRMArequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MSI_lib.SRLTService.createRMArequestResponse> createRMArequestAsync(MSI_lib.SRLTService.createRMArequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuotationConfirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QuotationConfirm(string vBarcode, string vQuoNo, string vStatusCode, string vRC, string vUserID, string vMSIMemo, string vCancelReason, string vRMANo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuotationConfirm", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QuotationConfirmAsync(string vBarcode, string vQuoNo, string vStatusCode, string vRC, string vUserID, string vMSIMemo, string vCancelReason, string vRMANo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBarcodeModelDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetBarcodeModelDesc(string v_Barocde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBarcodeModelDesc", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetBarcodeModelDescAsync(string v_Barocde);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class rmaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private S_rmaHeader s_newRMA_HField;
        
        private S_rmaAttachment s_newRMA_AField;
        
        private S_rmaLines[] s_newRMA_LField;
        
        private S_rmaLine_details[] s_newRMA_L_DField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public S_rmaHeader s_newRMA_H {
            get {
                return this.s_newRMA_HField;
            }
            set {
                this.s_newRMA_HField = value;
                this.RaisePropertyChanged("s_newRMA_H");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public S_rmaAttachment s_newRMA_A {
            get {
                return this.s_newRMA_AField;
            }
            set {
                this.s_newRMA_AField = value;
                this.RaisePropertyChanged("s_newRMA_A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public S_rmaLines[] s_newRMA_L {
            get {
                return this.s_newRMA_LField;
            }
            set {
                this.s_newRMA_LField = value;
                this.RaisePropertyChanged("s_newRMA_L");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public S_rmaLine_details[] s_newRMA_L_D {
            get {
                return this.s_newRMA_L_DField;
            }
            set {
                this.s_newRMA_L_DField = value;
                this.RaisePropertyChanged("s_newRMA_L_D");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class S_rmaHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rmanoField;
        
        private string seqnoField;
        
        private string customernoField;
        
        private string customernameField;
        
        private string customersiteField;
        
        private string contactField;
        
        private string contactemailField;
        
        private string requesteruidField;
        
        private string salesuidField;
        
        private string salesassistantuidField;
        
        private string createddateField;
        
        private string repaircenterField;
        
        private string estarrivaldateField;
        
        private string totalqtyField;
        
        private string refdocnoField;
        
        private string rmatypeField;
        
        private string statuscodeField;
        
        private string origrepaircenterField;
        
        private string isreadyforschedulingField;
        
        private string totalreceivedqtyField;
        
        private string totalrepairedqtyField;
        
        private string totalchangercqtyField;
        
        private string totalchangetypeqtyField;
        
        private string totalshippedqtyField;
        
        private string totalclosedqtyField;
        
        private string totalcreditedqtyField;
        
        private string currencycodeField;
        
        private string reasoncodeField;
        
        private string salesnameField;
        
        private string iserpcopyorderField;
        
        private string notesField;
        
        private string isreceivedelayField;
        
        private string isshipdelayField;
        
        private string actarrivaldateField;
        
        private string actshipdateField;
        
        private string origseqnoField;
        
        private string shippingmodeField;
        
        private string shiprcField;
        
        private string chkmodeField;
        
        private string chkmode2Field;
        
        private string requestdateField;
        
        private string referencenoField;
        
        private string tf_priceField;
        
        private string cm_addField;
        
        private string pickup_cm_addField;
        
        private string cm_phoneField;
        
        private string countryField;
        
        private string pickup_countryField;
        
        private string pick_upField;
        
        private string paymentField;
        
        private string payment_others_descField;
        
        private string pickup_cityField;
        
        private string cityField;
        
        private string townField;
        
        private string cm_add2Field;
        
        private string cm_add3Field;
        
        private string crc_data_tranField;
        
        private string cm_phone2Field;
        
        private string cm_faxnoField;
        
        private string shipment_remarkField;
        
        private string quoteviaField;
        
        private string postal_codeField;
        
        private string pickup_postal_codeField;
        
        private string account_idField;
        
        private string account_nameField;
        
        private string isbookingField;
        
        private string isonsiteField;
        
        private string ispickupField;
        
        private string transfertorcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rmano {
            get {
                return this.rmanoField;
            }
            set {
                this.rmanoField = value;
                this.RaisePropertyChanged("rmano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string seqno {
            get {
                return this.seqnoField;
            }
            set {
                this.seqnoField = value;
                this.RaisePropertyChanged("seqno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerno {
            get {
                return this.customernoField;
            }
            set {
                this.customernoField = value;
                this.RaisePropertyChanged("customerno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customername {
            get {
                return this.customernameField;
            }
            set {
                this.customernameField = value;
                this.RaisePropertyChanged("customername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string customersite {
            get {
                return this.customersiteField;
            }
            set {
                this.customersiteField = value;
                this.RaisePropertyChanged("customersite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string contactemail {
            get {
                return this.contactemailField;
            }
            set {
                this.contactemailField = value;
                this.RaisePropertyChanged("contactemail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string requesteruid {
            get {
                return this.requesteruidField;
            }
            set {
                this.requesteruidField = value;
                this.RaisePropertyChanged("requesteruid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string salesuid {
            get {
                return this.salesuidField;
            }
            set {
                this.salesuidField = value;
                this.RaisePropertyChanged("salesuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string salesassistantuid {
            get {
                return this.salesassistantuidField;
            }
            set {
                this.salesassistantuidField = value;
                this.RaisePropertyChanged("salesassistantuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string createddate {
            get {
                return this.createddateField;
            }
            set {
                this.createddateField = value;
                this.RaisePropertyChanged("createddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string repaircenter {
            get {
                return this.repaircenterField;
            }
            set {
                this.repaircenterField = value;
                this.RaisePropertyChanged("repaircenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string estarrivaldate {
            get {
                return this.estarrivaldateField;
            }
            set {
                this.estarrivaldateField = value;
                this.RaisePropertyChanged("estarrivaldate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string totalqty {
            get {
                return this.totalqtyField;
            }
            set {
                this.totalqtyField = value;
                this.RaisePropertyChanged("totalqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string refdocno {
            get {
                return this.refdocnoField;
            }
            set {
                this.refdocnoField = value;
                this.RaisePropertyChanged("refdocno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string rmatype {
            get {
                return this.rmatypeField;
            }
            set {
                this.rmatypeField = value;
                this.RaisePropertyChanged("rmatype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string statuscode {
            get {
                return this.statuscodeField;
            }
            set {
                this.statuscodeField = value;
                this.RaisePropertyChanged("statuscode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string origrepaircenter {
            get {
                return this.origrepaircenterField;
            }
            set {
                this.origrepaircenterField = value;
                this.RaisePropertyChanged("origrepaircenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string isreadyforscheduling {
            get {
                return this.isreadyforschedulingField;
            }
            set {
                this.isreadyforschedulingField = value;
                this.RaisePropertyChanged("isreadyforscheduling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string totalreceivedqty {
            get {
                return this.totalreceivedqtyField;
            }
            set {
                this.totalreceivedqtyField = value;
                this.RaisePropertyChanged("totalreceivedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string totalrepairedqty {
            get {
                return this.totalrepairedqtyField;
            }
            set {
                this.totalrepairedqtyField = value;
                this.RaisePropertyChanged("totalrepairedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string totalchangercqty {
            get {
                return this.totalchangercqtyField;
            }
            set {
                this.totalchangercqtyField = value;
                this.RaisePropertyChanged("totalchangercqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string totalchangetypeqty {
            get {
                return this.totalchangetypeqtyField;
            }
            set {
                this.totalchangetypeqtyField = value;
                this.RaisePropertyChanged("totalchangetypeqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string totalshippedqty {
            get {
                return this.totalshippedqtyField;
            }
            set {
                this.totalshippedqtyField = value;
                this.RaisePropertyChanged("totalshippedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string totalclosedqty {
            get {
                return this.totalclosedqtyField;
            }
            set {
                this.totalclosedqtyField = value;
                this.RaisePropertyChanged("totalclosedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string totalcreditedqty {
            get {
                return this.totalcreditedqtyField;
            }
            set {
                this.totalcreditedqtyField = value;
                this.RaisePropertyChanged("totalcreditedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string currencycode {
            get {
                return this.currencycodeField;
            }
            set {
                this.currencycodeField = value;
                this.RaisePropertyChanged("currencycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string reasoncode {
            get {
                return this.reasoncodeField;
            }
            set {
                this.reasoncodeField = value;
                this.RaisePropertyChanged("reasoncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string salesname {
            get {
                return this.salesnameField;
            }
            set {
                this.salesnameField = value;
                this.RaisePropertyChanged("salesname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string iserpcopyorder {
            get {
                return this.iserpcopyorderField;
            }
            set {
                this.iserpcopyorderField = value;
                this.RaisePropertyChanged("iserpcopyorder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string isreceivedelay {
            get {
                return this.isreceivedelayField;
            }
            set {
                this.isreceivedelayField = value;
                this.RaisePropertyChanged("isreceivedelay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string isshipdelay {
            get {
                return this.isshipdelayField;
            }
            set {
                this.isshipdelayField = value;
                this.RaisePropertyChanged("isshipdelay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string actarrivaldate {
            get {
                return this.actarrivaldateField;
            }
            set {
                this.actarrivaldateField = value;
                this.RaisePropertyChanged("actarrivaldate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string actshipdate {
            get {
                return this.actshipdateField;
            }
            set {
                this.actshipdateField = value;
                this.RaisePropertyChanged("actshipdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string origseqno {
            get {
                return this.origseqnoField;
            }
            set {
                this.origseqnoField = value;
                this.RaisePropertyChanged("origseqno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string shippingmode {
            get {
                return this.shippingmodeField;
            }
            set {
                this.shippingmodeField = value;
                this.RaisePropertyChanged("shippingmode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string shiprc {
            get {
                return this.shiprcField;
            }
            set {
                this.shiprcField = value;
                this.RaisePropertyChanged("shiprc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string chkmode {
            get {
                return this.chkmodeField;
            }
            set {
                this.chkmodeField = value;
                this.RaisePropertyChanged("chkmode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string chkmode2 {
            get {
                return this.chkmode2Field;
            }
            set {
                this.chkmode2Field = value;
                this.RaisePropertyChanged("chkmode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string requestdate {
            get {
                return this.requestdateField;
            }
            set {
                this.requestdateField = value;
                this.RaisePropertyChanged("requestdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string referenceno {
            get {
                return this.referencenoField;
            }
            set {
                this.referencenoField = value;
                this.RaisePropertyChanged("referenceno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string tf_price {
            get {
                return this.tf_priceField;
            }
            set {
                this.tf_priceField = value;
                this.RaisePropertyChanged("tf_price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string cm_add {
            get {
                return this.cm_addField;
            }
            set {
                this.cm_addField = value;
                this.RaisePropertyChanged("cm_add");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string pickup_cm_add {
            get {
                return this.pickup_cm_addField;
            }
            set {
                this.pickup_cm_addField = value;
                this.RaisePropertyChanged("pickup_cm_add");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string cm_phone {
            get {
                return this.cm_phoneField;
            }
            set {
                this.cm_phoneField = value;
                this.RaisePropertyChanged("cm_phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string pickup_country {
            get {
                return this.pickup_countryField;
            }
            set {
                this.pickup_countryField = value;
                this.RaisePropertyChanged("pickup_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string pick_up {
            get {
                return this.pick_upField;
            }
            set {
                this.pick_upField = value;
                this.RaisePropertyChanged("pick_up");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("payment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string payment_others_desc {
            get {
                return this.payment_others_descField;
            }
            set {
                this.payment_others_descField = value;
                this.RaisePropertyChanged("payment_others_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string pickup_city {
            get {
                return this.pickup_cityField;
            }
            set {
                this.pickup_cityField = value;
                this.RaisePropertyChanged("pickup_city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
                this.RaisePropertyChanged("town");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string cm_add2 {
            get {
                return this.cm_add2Field;
            }
            set {
                this.cm_add2Field = value;
                this.RaisePropertyChanged("cm_add2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string cm_add3 {
            get {
                return this.cm_add3Field;
            }
            set {
                this.cm_add3Field = value;
                this.RaisePropertyChanged("cm_add3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string crc_data_tran {
            get {
                return this.crc_data_tranField;
            }
            set {
                this.crc_data_tranField = value;
                this.RaisePropertyChanged("crc_data_tran");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string cm_phone2 {
            get {
                return this.cm_phone2Field;
            }
            set {
                this.cm_phone2Field = value;
                this.RaisePropertyChanged("cm_phone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string cm_faxno {
            get {
                return this.cm_faxnoField;
            }
            set {
                this.cm_faxnoField = value;
                this.RaisePropertyChanged("cm_faxno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string shipment_remark {
            get {
                return this.shipment_remarkField;
            }
            set {
                this.shipment_remarkField = value;
                this.RaisePropertyChanged("shipment_remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string quotevia {
            get {
                return this.quoteviaField;
            }
            set {
                this.quoteviaField = value;
                this.RaisePropertyChanged("quotevia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                this.postal_codeField = value;
                this.RaisePropertyChanged("postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string pickup_postal_code {
            get {
                return this.pickup_postal_codeField;
            }
            set {
                this.pickup_postal_codeField = value;
                this.RaisePropertyChanged("pickup_postal_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string account_id {
            get {
                return this.account_idField;
            }
            set {
                this.account_idField = value;
                this.RaisePropertyChanged("account_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string account_name {
            get {
                return this.account_nameField;
            }
            set {
                this.account_nameField = value;
                this.RaisePropertyChanged("account_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string isbooking {
            get {
                return this.isbookingField;
            }
            set {
                this.isbookingField = value;
                this.RaisePropertyChanged("isbooking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string isonsite {
            get {
                return this.isonsiteField;
            }
            set {
                this.isonsiteField = value;
                this.RaisePropertyChanged("isonsite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string ispickup {
            get {
                return this.ispickupField;
            }
            set {
                this.ispickupField = value;
                this.RaisePropertyChanged("ispickup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string transfertorc {
            get {
                return this.transfertorcField;
            }
            set {
                this.transfertorcField = value;
                this.RaisePropertyChanged("transfertorc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryFilterH : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string p_s_rcnameField;
        
        private string p_s_rmanoField;
        
        private string p_s_barcodeField;
        
        private string p_s_credit_rmanoField;
        
        private string p_s_cnnoField;
        
        private string p_s_tmpFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string p_s_rcname {
            get {
                return this.p_s_rcnameField;
            }
            set {
                this.p_s_rcnameField = value;
                this.RaisePropertyChanged("p_s_rcname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string p_s_rmano {
            get {
                return this.p_s_rmanoField;
            }
            set {
                this.p_s_rmanoField = value;
                this.RaisePropertyChanged("p_s_rmano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string p_s_barcode {
            get {
                return this.p_s_barcodeField;
            }
            set {
                this.p_s_barcodeField = value;
                this.RaisePropertyChanged("p_s_barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string p_s_credit_rmano {
            get {
                return this.p_s_credit_rmanoField;
            }
            set {
                this.p_s_credit_rmanoField = value;
                this.RaisePropertyChanged("p_s_credit_rmano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string p_s_cnno {
            get {
                return this.p_s_cnnoField;
            }
            set {
                this.p_s_cnnoField = value;
                this.RaisePropertyChanged("p_s_cnno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string p_s_tmpFlag {
            get {
                return this.p_s_tmpFlagField;
            }
            set {
                this.p_s_tmpFlagField = value;
                this.RaisePropertyChanged("p_s_tmpFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string p_s_login_idField;
        
        private string p_s_rcnameField;
        
        private string p_s_tel_noField;
        
        private string p_s_referencenoField;
        
        private string p_s_rmanoField;
        
        private string p_s_rmano2Field;
        
        private string p_s_barcodeField;
        
        private string p_s_lobField;
        
        private string p_s_modelField;
        
        private string p_s_countryField;
        
        private string p_s_customer_noField;
        
        private string p_s_customer_nameField;
        
        private string p_s_request_dateField;
        
        private string p_s_emailField;
        
        private string p_s_yearField;
        
        private string p_s_monthField;
        
        private string p_s_weekField;
        
        private string p_s_tmpFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string p_s_login_id {
            get {
                return this.p_s_login_idField;
            }
            set {
                this.p_s_login_idField = value;
                this.RaisePropertyChanged("p_s_login_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string p_s_rcname {
            get {
                return this.p_s_rcnameField;
            }
            set {
                this.p_s_rcnameField = value;
                this.RaisePropertyChanged("p_s_rcname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string p_s_tel_no {
            get {
                return this.p_s_tel_noField;
            }
            set {
                this.p_s_tel_noField = value;
                this.RaisePropertyChanged("p_s_tel_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string p_s_referenceno {
            get {
                return this.p_s_referencenoField;
            }
            set {
                this.p_s_referencenoField = value;
                this.RaisePropertyChanged("p_s_referenceno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string p_s_rmano {
            get {
                return this.p_s_rmanoField;
            }
            set {
                this.p_s_rmanoField = value;
                this.RaisePropertyChanged("p_s_rmano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string p_s_rmano2 {
            get {
                return this.p_s_rmano2Field;
            }
            set {
                this.p_s_rmano2Field = value;
                this.RaisePropertyChanged("p_s_rmano2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string p_s_barcode {
            get {
                return this.p_s_barcodeField;
            }
            set {
                this.p_s_barcodeField = value;
                this.RaisePropertyChanged("p_s_barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string p_s_lob {
            get {
                return this.p_s_lobField;
            }
            set {
                this.p_s_lobField = value;
                this.RaisePropertyChanged("p_s_lob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string p_s_model {
            get {
                return this.p_s_modelField;
            }
            set {
                this.p_s_modelField = value;
                this.RaisePropertyChanged("p_s_model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string p_s_country {
            get {
                return this.p_s_countryField;
            }
            set {
                this.p_s_countryField = value;
                this.RaisePropertyChanged("p_s_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string p_s_customer_no {
            get {
                return this.p_s_customer_noField;
            }
            set {
                this.p_s_customer_noField = value;
                this.RaisePropertyChanged("p_s_customer_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string p_s_customer_name {
            get {
                return this.p_s_customer_nameField;
            }
            set {
                this.p_s_customer_nameField = value;
                this.RaisePropertyChanged("p_s_customer_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string p_s_request_date {
            get {
                return this.p_s_request_dateField;
            }
            set {
                this.p_s_request_dateField = value;
                this.RaisePropertyChanged("p_s_request_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string p_s_email {
            get {
                return this.p_s_emailField;
            }
            set {
                this.p_s_emailField = value;
                this.RaisePropertyChanged("p_s_email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string p_s_year {
            get {
                return this.p_s_yearField;
            }
            set {
                this.p_s_yearField = value;
                this.RaisePropertyChanged("p_s_year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string p_s_month {
            get {
                return this.p_s_monthField;
            }
            set {
                this.p_s_monthField = value;
                this.RaisePropertyChanged("p_s_month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string p_s_week {
            get {
                return this.p_s_weekField;
            }
            set {
                this.p_s_weekField = value;
                this.RaisePropertyChanged("p_s_week");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string p_s_tmpFlag {
            get {
                return this.p_s_tmpFlagField;
            }
            set {
                this.p_s_tmpFlagField = value;
                this.RaisePropertyChanged("p_s_tmpFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class S_rmaLine_details : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rmanoField;
        
        private string linenoField;
        
        private string line_detail_idField;
        
        private string barcodeField;
        
        private string is_receivedField;
        
        private string is_shippedField;
        
        private string warrantyField;
        
        private string customer_job_numberField;
        
        private string repaircenterField;
        
        private string fault_descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rmano {
            get {
                return this.rmanoField;
            }
            set {
                this.rmanoField = value;
                this.RaisePropertyChanged("rmano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string lineno {
            get {
                return this.linenoField;
            }
            set {
                this.linenoField = value;
                this.RaisePropertyChanged("lineno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string line_detail_id {
            get {
                return this.line_detail_idField;
            }
            set {
                this.line_detail_idField = value;
                this.RaisePropertyChanged("line_detail_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string is_received {
            get {
                return this.is_receivedField;
            }
            set {
                this.is_receivedField = value;
                this.RaisePropertyChanged("is_received");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string is_shipped {
            get {
                return this.is_shippedField;
            }
            set {
                this.is_shippedField = value;
                this.RaisePropertyChanged("is_shipped");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
                this.RaisePropertyChanged("warranty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string customer_job_number {
            get {
                return this.customer_job_numberField;
            }
            set {
                this.customer_job_numberField = value;
                this.RaisePropertyChanged("customer_job_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string repaircenter {
            get {
                return this.repaircenterField;
            }
            set {
                this.repaircenterField = value;
                this.RaisePropertyChanged("repaircenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string fault_description {
            get {
                return this.fault_descriptionField;
            }
            set {
                this.fault_descriptionField = value;
                this.RaisePropertyChanged("fault_description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class S_rmaLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rmanoField;
        
        private string seqnoField;
        
        private string linenoField;
        
        private string productField;
        
        private string modelField;
        
        private string requestedqtyField;
        
        private string receivedqtyField;
        
        private string repairedqtyField;
        
        private string erpqtyField;
        
        private string shippedqtyField;
        
        private string uomField;
        
        private string unitpriceField;
        
        private string currencycodeField;
        
        private string statuscodeField;
        
        private string changercqtyField;
        
        private string changetypeqtyField;
        
        private string itemidField;
        
        private string origlinenoField;
        
        private string sfincomeqtyField;
        
        private string creditedqtyField;
        
        private string closedqtyField;
        
        private string chargedqtyField;
        
        private string holdqtyField;
        
        private string repaircenterField;
        
        private string customerpartnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rmano {
            get {
                return this.rmanoField;
            }
            set {
                this.rmanoField = value;
                this.RaisePropertyChanged("rmano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string seqno {
            get {
                return this.seqnoField;
            }
            set {
                this.seqnoField = value;
                this.RaisePropertyChanged("seqno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lineno {
            get {
                return this.linenoField;
            }
            set {
                this.linenoField = value;
                this.RaisePropertyChanged("lineno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
                this.RaisePropertyChanged("product");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string requestedqty {
            get {
                return this.requestedqtyField;
            }
            set {
                this.requestedqtyField = value;
                this.RaisePropertyChanged("requestedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string receivedqty {
            get {
                return this.receivedqtyField;
            }
            set {
                this.receivedqtyField = value;
                this.RaisePropertyChanged("receivedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string repairedqty {
            get {
                return this.repairedqtyField;
            }
            set {
                this.repairedqtyField = value;
                this.RaisePropertyChanged("repairedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string erpqty {
            get {
                return this.erpqtyField;
            }
            set {
                this.erpqtyField = value;
                this.RaisePropertyChanged("erpqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string shippedqty {
            get {
                return this.shippedqtyField;
            }
            set {
                this.shippedqtyField = value;
                this.RaisePropertyChanged("shippedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
                this.RaisePropertyChanged("uom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string unitprice {
            get {
                return this.unitpriceField;
            }
            set {
                this.unitpriceField = value;
                this.RaisePropertyChanged("unitprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string currencycode {
            get {
                return this.currencycodeField;
            }
            set {
                this.currencycodeField = value;
                this.RaisePropertyChanged("currencycode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string statuscode {
            get {
                return this.statuscodeField;
            }
            set {
                this.statuscodeField = value;
                this.RaisePropertyChanged("statuscode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string changercqty {
            get {
                return this.changercqtyField;
            }
            set {
                this.changercqtyField = value;
                this.RaisePropertyChanged("changercqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string changetypeqty {
            get {
                return this.changetypeqtyField;
            }
            set {
                this.changetypeqtyField = value;
                this.RaisePropertyChanged("changetypeqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string itemid {
            get {
                return this.itemidField;
            }
            set {
                this.itemidField = value;
                this.RaisePropertyChanged("itemid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string origlineno {
            get {
                return this.origlinenoField;
            }
            set {
                this.origlinenoField = value;
                this.RaisePropertyChanged("origlineno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string sfincomeqty {
            get {
                return this.sfincomeqtyField;
            }
            set {
                this.sfincomeqtyField = value;
                this.RaisePropertyChanged("sfincomeqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string creditedqty {
            get {
                return this.creditedqtyField;
            }
            set {
                this.creditedqtyField = value;
                this.RaisePropertyChanged("creditedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string closedqty {
            get {
                return this.closedqtyField;
            }
            set {
                this.closedqtyField = value;
                this.RaisePropertyChanged("closedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string chargedqty {
            get {
                return this.chargedqtyField;
            }
            set {
                this.chargedqtyField = value;
                this.RaisePropertyChanged("chargedqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string holdqty {
            get {
                return this.holdqtyField;
            }
            set {
                this.holdqtyField = value;
                this.RaisePropertyChanged("holdqty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string repaircenter {
            get {
                return this.repaircenterField;
            }
            set {
                this.repaircenterField = value;
                this.RaisePropertyChanged("repaircenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string customerpartno {
            get {
                return this.customerpartnoField;
            }
            set {
                this.customerpartnoField = value;
                this.RaisePropertyChanged("customerpartno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class S_rmaAttachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileidField;
        
        private string rmanoField;
        
        private string filenameField;
        
        private string filesizeField;
        
        private string filetypeField;
        
        private string noteField;
        
        private string creatoruidField;
        
        private string createdtimeField;
        
        private string rc_nameField;
        
        private string flagField;
        
        private string filepathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileid {
            get {
                return this.fileidField;
            }
            set {
                this.fileidField = value;
                this.RaisePropertyChanged("fileid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string rmano {
            get {
                return this.rmanoField;
            }
            set {
                this.rmanoField = value;
                this.RaisePropertyChanged("rmano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string filesize {
            get {
                return this.filesizeField;
            }
            set {
                this.filesizeField = value;
                this.RaisePropertyChanged("filesize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string filetype {
            get {
                return this.filetypeField;
            }
            set {
                this.filetypeField = value;
                this.RaisePropertyChanged("filetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string creatoruid {
            get {
                return this.creatoruidField;
            }
            set {
                this.creatoruidField = value;
                this.RaisePropertyChanged("creatoruid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string createdtime {
            get {
                return this.createdtimeField;
            }
            set {
                this.createdtimeField = value;
                this.RaisePropertyChanged("createdtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string rc_name {
            get {
                return this.rc_nameField;
            }
            set {
                this.rc_nameField = value;
                this.RaisePropertyChanged("rc_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string filepath {
            get {
                return this.filepathField;
            }
            set {
                this.filepathField = value;
                this.RaisePropertyChanged("filepath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createRMArequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createRMArequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MSI_lib.SRLTService.rmaRequest s_newRMA;
        
        public createRMArequestRequest() {
        }
        
        public createRMArequestRequest(MSI_lib.SRLTService.rmaRequest s_newRMA) {
            this.s_newRMA = s_newRMA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createRMArequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createRMArequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool createRMArequestResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string s_rmano;
        
        public createRMArequestResponse() {
        }
        
        public createRMArequestResponse(bool createRMArequestResult, string s_rmano) {
            this.createRMArequestResult = createRMArequestResult;
            this.s_rmano = s_rmano;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ASPUploadProcessSoapChannel : MSI_lib.SRLTService.ASPUploadProcessSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ASPUploadProcessSoapClient : System.ServiceModel.ClientBase<MSI_lib.SRLTService.ASPUploadProcessSoap>, MSI_lib.SRLTService.ASPUploadProcessSoap {
        
        public ASPUploadProcessSoapClient() {
        }
        
        public ASPUploadProcessSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ASPUploadProcessSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASPUploadProcessSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASPUploadProcessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetMSIModel(string s_model, string s_marketname) {
            return base.Channel.GetMSIModel(s_model, s_marketname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMSIModelAsync(string s_model, string s_marketname) {
            return base.Channel.GetMSIModelAsync(s_model, s_marketname);
        }
        
        public System.Data.DataSet Phone_Area(string vCountry, string vType, string vNumber) {
            return base.Channel.Phone_Area(vCountry, vType, vNumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Phone_AreaAsync(string vCountry, string vType, string vNumber) {
            return base.Channel.Phone_AreaAsync(vCountry, vType, vNumber);
        }
        
        public System.Data.DataSet Parts_Onhand(string vRC, string vModel) {
            return base.Channel.Parts_Onhand(vRC, vModel);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Parts_OnhandAsync(string vRC, string vModel) {
            return base.Channel.Parts_OnhandAsync(vRC, vModel);
        }
        
        public System.Data.DataSet Parts_Price(string vRC, string vModel) {
            return base.Channel.Parts_Price(vRC, vModel);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Parts_PriceAsync(string vRC, string vModel) {
            return base.Channel.Parts_PriceAsync(vRC, vModel);
        }
        
        public System.Data.DataTable GetMSICNModelPrice(string vRC, string vModel, string vMarketname) {
            return base.Channel.GetMSICNModelPrice(vRC, vModel, vMarketname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetMSICNModelPriceAsync(string vRC, string vModel, string vMarketname) {
            return base.Channel.GetMSICNModelPriceAsync(vRC, vModel, vMarketname);
        }
        
        public string updateRMArequest(MSI_lib.SRLTService.rmaRequest s_newRMA) {
            return base.Channel.updateRMArequest(s_newRMA);
        }
        
        public System.Threading.Tasks.Task<string> updateRMArequestAsync(MSI_lib.SRLTService.rmaRequest s_newRMA) {
            return base.Channel.updateRMArequestAsync(s_newRMA);
        }
        
        public System.Data.DataSet getSRLTStatusList(MSI_lib.SRLTService.QueryFilter qf_cond) {
            return base.Channel.getSRLTStatusList(qf_cond);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getSRLTStatusListAsync(MSI_lib.SRLTService.QueryFilter qf_cond) {
            return base.Channel.getSRLTStatusListAsync(qf_cond);
        }
        
        public System.Data.DataTable getQuotationOBC() {
            return base.Channel.getQuotationOBC();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getQuotationOBCAsync() {
            return base.Channel.getQuotationOBCAsync();
        }
        
        public System.Data.DataTable getQuotationDeatil(string vQuotationno, string vRC) {
            return base.Channel.getQuotationDeatil(vQuotationno, vRC);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getQuotationDeatilAsync(string vQuotationno, string vRC) {
            return base.Channel.getQuotationDeatilAsync(vQuotationno, vRC);
        }
        
        public System.Data.DataTable getSRLTStatusForIVR(MSI_lib.SRLTService.QueryFilter vQueryFilter) {
            return base.Channel.getSRLTStatusForIVR(vQueryFilter);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getSRLTStatusForIVRAsync(MSI_lib.SRLTService.QueryFilter vQueryFilter) {
            return base.Channel.getSRLTStatusForIVRAsync(vQueryFilter);
        }
        
        public System.Data.DataTable getSRLTStatusForWeb(MSI_lib.SRLTService.QueryFilter vQueryFilter) {
            return base.Channel.getSRLTStatusForWeb(vQueryFilter);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getSRLTStatusForWebAsync(MSI_lib.SRLTService.QueryFilter vQueryFilter) {
            return base.Channel.getSRLTStatusForWebAsync(vQueryFilter);
        }
        
        public System.Data.DataSet CheckBookingRMANO(string vRMANO) {
            return base.Channel.CheckBookingRMANO(vRMANO);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CheckBookingRMANOAsync(string vRMANO) {
            return base.Channel.CheckBookingRMANOAsync(vRMANO);
        }
        
        public System.Data.DataSet GetPelicanEDI(string vrepaircenter, string begindate, string enddate, string inout) {
            return base.Channel.GetPelicanEDI(vrepaircenter, begindate, enddate, inout);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPelicanEDIAsync(string vrepaircenter, string begindate, string enddate, string inout) {
            return base.Channel.GetPelicanEDIAsync(vrepaircenter, begindate, enddate, inout);
        }
        
        public System.Data.DataSet GetOffDate(string vCountry) {
            return base.Channel.GetOffDate(vCountry);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOffDateAsync(string vCountry) {
            return base.Channel.GetOffDateAsync(vCountry);
        }
        
        public System.Data.DataSet GetServiceInfo(string vCountry) {
            return base.Channel.GetServiceInfo(vCountry);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetServiceInfoAsync(string vCountry) {
            return base.Channel.GetServiceInfoAsync(vCountry);
        }
        
        public System.Data.DataSet GetBookingTbl(string vcountry, string vsc, string begindate, string enddate) {
            return base.Channel.GetBookingTbl(vcountry, vsc, begindate, enddate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBookingTblAsync(string vcountry, string vsc, string begindate, string enddate) {
            return base.Channel.GetBookingTblAsync(vcountry, vsc, begindate, enddate);
        }
        
        public string PickupBookingAdd(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark) {
            return base.Channel.PickupBookingAdd(vcountry, vsc, vbookingdate, vsession, vRMANO, vcustomer, vmail, vphone, vuesr, vBarcode, vModel, vremark);
        }
        
        public System.Threading.Tasks.Task<string> PickupBookingAddAsync(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark) {
            return base.Channel.PickupBookingAddAsync(vcountry, vsc, vbookingdate, vsession, vRMANO, vcustomer, vmail, vphone, vuesr, vBarcode, vModel, vremark);
        }
        
        public string PickupBookingDelete(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark) {
            return base.Channel.PickupBookingDelete(vcountry, vsc, vbookingdate, vsession, vRMANO, vcustomer, vmail, vphone, vuesr, vBarcode, vModel, vremark);
        }
        
        public System.Threading.Tasks.Task<string> PickupBookingDeleteAsync(string vcountry, string vsc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark) {
            return base.Channel.PickupBookingDeleteAsync(vcountry, vsc, vbookingdate, vsession, vRMANO, vcustomer, vmail, vphone, vuesr, vBarcode, vModel, vremark);
        }
        
        public string RMABookingAdd(string vsc, string vbookingdate, string vsession, MSI_lib.SRLTService.rmaRequest s_newRMA) {
            return base.Channel.RMABookingAdd(vsc, vbookingdate, vsession, s_newRMA);
        }
        
        public System.Threading.Tasks.Task<string> RMABookingAddAsync(string vsc, string vbookingdate, string vsession, MSI_lib.SRLTService.rmaRequest s_newRMA) {
            return base.Channel.RMABookingAddAsync(vsc, vbookingdate, vsession, s_newRMA);
        }
        
        public string RMABookingDelete(string vcountry, string vsc, string vrc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark) {
            return base.Channel.RMABookingDelete(vcountry, vsc, vrc, vbookingdate, vsession, vRMANO, vcustomer, vmail, vphone, vuesr, vBarcode, vModel, vremark);
        }
        
        public System.Threading.Tasks.Task<string> RMABookingDeleteAsync(string vcountry, string vsc, string vrc, string vbookingdate, string vsession, string vRMANO, string vcustomer, string vmail, string vphone, string vuesr, string vBarcode, string vModel, string vremark) {
            return base.Channel.RMABookingDeleteAsync(vcountry, vsc, vrc, vbookingdate, vsession, vRMANO, vcustomer, vmail, vphone, vuesr, vBarcode, vModel, vremark);
        }
        
        public System.Data.DataSet getSRLTWarrantyInfo(MSI_lib.SRLTService.QueryFilterH qf_cond) {
            return base.Channel.getSRLTWarrantyInfo(qf_cond);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getSRLTWarrantyInfoAsync(MSI_lib.SRLTService.QueryFilterH qf_cond) {
            return base.Channel.getSRLTWarrantyInfoAsync(qf_cond);
        }
        
        public string chkbarcoderequest(string vBarcode) {
            return base.Channel.chkbarcoderequest(vBarcode);
        }
        
        public System.Threading.Tasks.Task<string> chkbarcoderequestAsync(string vBarcode) {
            return base.Channel.chkbarcoderequestAsync(vBarcode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSI_lib.SRLTService.createRMArequestResponse MSI_lib.SRLTService.ASPUploadProcessSoap.createRMArequest(MSI_lib.SRLTService.createRMArequestRequest request) {
            return base.Channel.createRMArequest(request);
        }
        
        public bool createRMArequest(MSI_lib.SRLTService.rmaRequest s_newRMA, out string s_rmano) {
            MSI_lib.SRLTService.createRMArequestRequest inValue = new MSI_lib.SRLTService.createRMArequestRequest();
            inValue.s_newRMA = s_newRMA;
            MSI_lib.SRLTService.createRMArequestResponse retVal = ((MSI_lib.SRLTService.ASPUploadProcessSoap)(this)).createRMArequest(inValue);
            s_rmano = retVal.s_rmano;
            return retVal.createRMArequestResult;
        }
        
        public System.Threading.Tasks.Task<MSI_lib.SRLTService.createRMArequestResponse> createRMArequestAsync(MSI_lib.SRLTService.createRMArequestRequest request) {
            return base.Channel.createRMArequestAsync(request);
        }
        
        public string QuotationConfirm(string vBarcode, string vQuoNo, string vStatusCode, string vRC, string vUserID, string vMSIMemo, string vCancelReason, string vRMANo) {
            return base.Channel.QuotationConfirm(vBarcode, vQuoNo, vStatusCode, vRC, vUserID, vMSIMemo, vCancelReason, vRMANo);
        }
        
        public System.Threading.Tasks.Task<string> QuotationConfirmAsync(string vBarcode, string vQuoNo, string vStatusCode, string vRC, string vUserID, string vMSIMemo, string vCancelReason, string vRMANo) {
            return base.Channel.QuotationConfirmAsync(vBarcode, vQuoNo, vStatusCode, vRC, vUserID, vMSIMemo, vCancelReason, vRMANo);
        }
        
        public string[] GetBarcodeModelDesc(string v_Barocde) {
            return base.Channel.GetBarcodeModelDesc(v_Barocde);
        }
        
        public System.Threading.Tasks.Task<string[]> GetBarcodeModelDescAsync(string v_Barocde) {
            return base.Channel.GetBarcodeModelDescAsync(v_Barocde);
        }
    }
}
